# import.R
library(scales)

tbl <- list.files(path = "./data", pattern = "*ajo.csv") %>% 
  paste0("data/", .) %>% 
  map_df(~read_csv2(.)) %>% 
  filter(!site_id == "null")

colnames(tbl) <- c("site.id",
                   "package.id",
                   "package.name",
                   "package.status",
                   "start.date",
                   "deadline",
                   "estimated.completion",
                   "completed",
                   "work.amount.est",
                   "work.amount.realization",
                   "tilannekuva",
                   "covid19.tehohoito.ja.tehovalvonta",
                   "covid19.vuodeosasto",
                   "kaikki.potilaat.tehohoito.ja.tehovalvonta",
                   "kaikki.potilaat.vuodeosasto",
                   "potilaita.teholle.covid19",
                   "potilaita.teholle.non.covid19",
                   "covid19.kuolleet",
                   "puutteet.muut.tarvikkeet",
                   "puutteet.muut.laakkeet",
                   "muut.huomiot",
                   "toiminnalliset.muutokset",
                   "pvm",
                   "covid19.potilaat.yhteensa",
                   "covid19.kotiutuneet",
                   "sairaansijat",
                   "tehohoito.ja.tehovaltonta.paikat",
                   "tietotekniset.hairiot",
                   "uudet.positiiviset.covid19.testit",
                   "vaje.antibiooteista",
                   "vaje.infuusioliuokset",
                   "vaje.kipulaakkeista",
                   "vaje.kasidesista",
                   "vaje.hapesta",
                   "vaje.maskeista",
                   "vaje.muut.kriittiset.laakkeet",
                   "vaje.muut.kriittiset.tarvikkeet",
                   "vaje.sedatiivat",
                   "vaje.suojakasineet",
                   "vaje.suojatakeista",
                   "vaje.verenkierrontuki",
                   "vaje.verituotteet",
                   "vaje.visiirit",
                   "vaje.hoitohenkilokunta",
                   "vaje.laakarit",
                   "vaje.muu.henkilokunta",
                   "lisatiedot")

tbl <- tbl %>% 
  mutate(pvm = as.Date(pvm, format = "%d.%m.%Y")) %>% 
  mutate(site.id = case_when(site.id == "4531569" ~ "KYS",
                             site.id == "4531565" ~ "SiunSote",
                             site.id == "4531567" ~ "Sosteri",
                             site.id == "4531583" ~ "ESSOTE",
                             site.id == "4531577" ~ "KSSHP",
                             TRUE ~ site.id),
         sairaansijat = as.numeric(sairaansijat),
         kaikki.potilaat.vuodeosasto = as.numeric(kaikki.potilaat.vuodeosasto),
         tehohoito.ja.tehovaltonta.paikat = as.numeric(tehohoito.ja.tehovaltonta.paikat),
         kaikki.potilaat.tehohoito.ja.tehovalvonta = as.numeric(kaikki.potilaat.tehohoito.ja.tehovalvonta),
         sairaala.kuormitus = percent(kaikki.potilaat.vuodeosasto / sairaansijat),
         teho.kuormitus = percent(kaikki.potilaat.tehohoito.ja.tehovalvonta / tehohoito.ja.tehovaltonta.paikat)) %>% 
  select(pvm, site.id, 
         sairaansijat, 
         kaikki.potilaat.vuodeosasto, 
         tehohoito.ja.tehovaltonta.paikat, 
         kaikki.potilaat.tehohoito.ja.tehovalvonta,
         covid19.kotiutuneet,
         uudet.positiiviset.covid19.testit, 
         covid19.kuolleet, 
         potilaita.teholle.covid19,
         potilaita.teholle.non.covid19, 
         covid19.potilaat.yhteensa, 
         covid19.vuodeosasto,
         covid19.tehohoito.ja.tehovalvonta,
         sairaala.kuormitus,
         teho.kuormitus,
         vaje.laakarit, vaje.hoitohenkilokunta, vaje.muu.henkilokunta,
         vaje.suojatakeista, vaje.visiirit,
         vaje.maskeista, vaje.suojakasineet, vaje.kasidesista,
         vaje.muut.kriittiset.tarvikkeet, 
         tietotekniset.hairiot,
         puutteet.muut.tarvikkeet,
         vaje.infuusioliuokset, vaje.verituotteet, vaje.hapesta, vaje.kipulaakkeista,
         vaje.sedatiivat, vaje.verenkierrontuki,vaje.antibiooteista, vaje.muut.kriittiset.laakkeet,
         puutteet.muut.laakkeet, toiminnalliset.muutokset,
         muut.huomiot) %>% 
  filter(!is.na(pvm))
  # mutate(vaje.laakarit = ifelse(vaje.laakarit == 1, as.character("Yes"), "No"),
  #        vaje.hoitohenkilokunta = ifelse(vaje.hoitohenkilokunta == 1, as.character("Yes"), "No"),
  #        vaje.muu.henkilokunta = ifelse(vaje.muu.henkilokunta == 1, as.character("Yes"), "No"),
  #        vaje.maskeista = ifelse(vaje.maskeista == 1, as.character("Yes"), "No"),
  #        vaje.visiirit = ifelse(vaje.visiirit == 1, as.character("Yes"), "No"),
  #        vaje.suojakasineet = ifelse(vaje.suojakasineet == 1, as.character("Yes"), "No"),
  #        vaje.kasidesista = ifelse(vaje.kasidesista == 1, as.character("Yes"), "No"),
  #        vaje.muut.kriittiset.tarvikkeet = ifelse(vaje.muut.kriittiset.tarvikkeet == 1, as.character("Yes"), "No"),
  #        vaje.infuusioliuokset = ifelse(vaje.infuusioliuokset == 1, as.character("Yes"), "No"),
  #        vaje.verituotteet = ifelse(vaje.verituotteet == 1, as.character("Yes"), "No"),
  #        vaje.hapesta = ifelse(vaje.hapesta == 1, as.character("Yes"), "No"),
  #        vaje.kipulaakkeista = ifelse(vaje.kipulaakkeista == 1, as.character("Yes"), "No"),
  #        vaje.sedatiivat = ifelse(vaje.sedatiivat == 1, as.character("Yes"), "No"),
  #        vaje.verenkierrontuki = ifelse(vaje.verenkierrontuki == 1, as.character("Yes"), "No"),
  #        vaje.antibiooteista = ifelse(vaje.antibiooteista == 1, as.character("Yes"), "No"),
  #        vaje.muut.kriittiset.laakkeet = ifelse(vaje.muut.kriittiset.laakkeet == 1, as.character("Yes"), "No"),
  #        puutteet.muut.laakkeet = ifelse(!is.na(puutteet.muut.laakkeet), puutteet.muut.laakkeet, ""),
  #        puutteet.muut.tarvikkeet = ifelse(!is.na(puutteet.muut.tarvikkeet), puutteet.muut.tarvikkeet, ""),
  #        vaje.suojatakeista = ifelse(vaje.suojatakeista == 1, as.character("Yes"), "No"),
  #        tietotekniset.hairiot = ifelse(tietotekniset.hairiot == 1, as.character("Yes"), "No"))