# import.R
library(scales)

tbl <- list.files(path = "./data", pattern = "*ajo.csv") %>% 
  paste0("data/", .) %>% 
  map_df(~read_csv2(.)) %>% 
  filter(!site_id == "null")

colnames(tbl) <- c("site.id",
                   "package.id",
                   "package.name",
                   "package.status",
                   "start.date",
                   "deadline",
                   "estimated.completion",
                   "completed",
                   "work.amount.est",
                   "work.amount.realization",
                   "tilannekuva",
                   "covid19.tehohoito.ja.tehovalvonta",
                   "covid19.vuodeosasto",
                   "covid19.0_9",
                   "covid19.10_19",
                   "covid19.20_29",
                   "covid19.30_39",
                   "covid19.40_49",
                   "covid19.50_59",
                   "covid19.60_69",
                   "covid19.70_79",
                   "covid19.80",
                   "joukko.altistuneet",
                   "kaikki.potilaat.tehohoito.ja.tehovalvonta",
                   "kaikki.potilaat.vuodeosasto",
                   "karanteeni.alkoi",
                   "tartunnan.lahde.tiedossa",
                   "karanteeni.maaratty.muu.shp",
                   "karanteeni.maaratty.oma.shp",
                   "covid19.kuolleet.esh",
                   "covid19.kuolleet.koti",
                   "covid19.kuolleet.pth",
                   "covid19.kuolleet.so",
                   "muut.huomiot",
                   "muut.huomiot.karanteeni",
                   "toiminnalliset.muutokset",
                   "pvm",
                   "covid19.potilaat.yhteensa",
                   "sairaansijat",
                   "tehohoito.ja.tehovaltonta.paikat",
                   "vaje.hoitohenkilokunta",
                   "vaje.laakarit",
                   "vaje.muu.henkilokunta",
                   "lisatiedot")

tbl <- tbl %>% 
  mutate(pvm = as.Date(pvm, format = "%d.%m.%Y")) %>% 
  mutate(site.id = case_when(site.id == "4531569" ~ "KYS",
                             site.id == "4531565" ~ "SiunSote",
                             site.id == "4531567" ~ "Sosteri",
                             site.id == "4531583" ~ "ESSOTE",
                             site.id == "4531577" ~ "KSSHP",
                             TRUE ~ site.id),
         sairaansijat = as.numeric(sairaansijat),
         kaikki.potilaat.vuodeosasto = as.numeric(kaikki.potilaat.vuodeosasto),
         tehohoito.ja.tehovaltonta.paikat = as.numeric(tehohoito.ja.tehovaltonta.paikat),
         kaikki.potilaat.tehohoito.ja.tehovalvonta = as.numeric(kaikki.potilaat.tehohoito.ja.tehovalvonta),
         sairaala.kuormitus = percent(kaikki.potilaat.vuodeosasto / sairaansijat),
         teho.kuormitus = percent(kaikki.potilaat.tehohoito.ja.tehovalvonta / tehohoito.ja.tehovaltonta.paikat)) %>% 
  select(pvm, site.id, 
         sairaansijat, 
         kaikki.potilaat.vuodeosasto, 
         tehohoito.ja.tehovaltonta.paikat, 
         kaikki.potilaat.tehohoito.ja.tehovalvonta,
         covid19.kuolleet.esh,
         covid19.kuolleet.pth,
         covid19.kuolleet.so,
         covid19.kuolleet.koti,
         covid19.potilaat.yhteensa, 
         covid19.vuodeosasto,
         covid19.tehohoito.ja.tehovalvonta,
         sairaala.kuormitus,
         teho.kuormitus,
         covid19.0_9,
         covid19.10_19,
         covid19.20_29,
         covid19.30_39,
         covid19.40_49,
         covid19.50_59,
         covid19.60_69,
         covid19.70_79,
         covid19.80,
         vaje.laakarit, vaje.hoitohenkilokunta, vaje.muu.henkilokunta,
         toiminnalliset.muutokset,
         muut.huomiot,
         karanteeni.maaratty.oma.shp,
         karanteeni.maaratty.muu.shp,
         karanteeni.alkoi,
         tartunnan.lahde.tiedossa,
         joukko.altistuneet,
         muut.huomiot.karanteeni) %>% 
  filter(!is.na(pvm))
